# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='labadiena!'),
        ),
    ]
